### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

### ISSUE THREAD

**Issue by Halvar10** [codedevote/devspace2017#1]
Hi,
danke für die Images! Ich freue mich auf morgen.

Jeder Versuch, die Images aus der Vagrant-Cloud runterzuladen endet bei mir nach einiger Zeit mit 

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

was wohl "Server refuses request" bedeutet.  Hab es jetzt vielleicht 10 mal probiert, am Anfang nach dem Kommando "vagrant up" lädt er auch immer lustig vor sich hin, aber nach irgendwo zwischen 10 und 30 % bricht er mit dem Fehler ab. Ich versuche es später nochmal von der Firma aus, aber ich glaube gerade nicht, dass meine Internetverbindung das Problem ist. 

Wäre es möglich, die images nochmal irgendwo alternativ zur Verfügung zu stellen? Ich sehe sonst gerade für morgen für mich schwarz... ;-)

Danke & VG Marcus

**Comment by codedevote** [comment]
Ich bin gerade auf dem Weg nach Leipzig, versuche noch einen Upload ins Onedrive zu starten. Du kannst die Box dann mit vagrant box add hinzufügen. Siehe hier: https://www.vagrantup.com/docs/cli/box.html#box-add

Ich poste den Link zur Box hier, sobald der Upload durch ist. Im Notfall habe ich die Box auch noch auf USB Stick dabei, dann kommst Du einfach schon ein bisschen vorher zum Workshop und wir machens damit.

**Comment by Halvar10** [comment]
Klingt gut, danke! Ich versuche es auch weiter.

**Comment by Halvar10** [comment]
Das ganze hat sich bei mir erledigt, vom Büro aus hat es jetzt geklappt. Danke für die Hilfe und bis morgen!
